### ISSUE TITLE
/bsb challenge cimport bug

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/addon-challenges#16]
Hi, I've problem with importing challenges

`29.09 17:54:33 [Server] ERROR null
29.09 17:54:33 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'bsb challenges cimport' in bentobox.addon.bskyblock.commands.AdminCommand(bsbadmin)
29.09 17:54:33 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1770) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1574) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
29.09 17:54:33 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
29.09 17:54:33 [Server] INFO Caused by: java.lang.NullPointerException
29.09 17:54:33 [Server] INFO at bentobox.addon.challenges.FreshSqueezedChallenges.parseItems(FreshSqueezedChallenges.java:180) ~[?:?]
29.09 17:54:33 [Server] INFO at bentobox.addon.challenges.FreshSqueezedChallenges.makeChallenges(FreshSqueezedChallenges.java:145) ~[?:?]
29.09 17:54:33 [Server] INFO at bentobox.addon.challenges.FreshSqueezedChallenges.importChallenges(FreshSqueezedChallenges.java:67) ~[?:?]
29.09 17:54:33 [Server] INFO at bentobox.addon.challenges.commands.admin.ImportCommand.execute(ImportCommand.java:26) ~[?:?]
29.09 17:54:33 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:236) ~[?:?]
29.09 17:54:33 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-1.13.1-b301.jar:git-Paper-301]
29.09 17:54:33 [Server] INFO ... 14 more
`

**Comment by Kryniowesegryderiusz** [comment]
Nvm, there was a bug in challenges.yml not containing rewardText. Error in console was misleading.
