### ISSUE TITLE
[Challenges] type island not working with entities

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/addon-challenges#17]
**Describe the bug**
When i set type: island and there i use witch, golem or either armorstand for requirement it does not work and makes error in console

Paper(327) 1.13.1-R0.1-SNAPSHOT

BSkyBlock 0.1
BentoBox-Challenges 0.1
BentoBox version 0.9.0-alpha2

`03.10 18:18:24 [Server] ERROR Could not pass event InventoryClickEvent to BentoBox v0.9.0-alpha2
03.10 18:18:24 [Server] INFO org.bukkit.event.EventException: null
03.10 18:18:24 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2257) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
03.10 18:18:24 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
03.10 18:18:24 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
03.10 18:18:24 [Server] INFO Caused by: java.lang.IllegalArgumentException: Specified map is empty
03.10 18:18:24 [Server] INFO at java.util.EnumMap.<init>(EnumMap.java:177) ~[?:1.8.0_181]
03.10 18:18:24 [Server] INFO at bentobox.addon.challenges.panel.TryToComplete.searchForBlocks(TryToComplete.java:180) ~[?:?]
03.10 18:18:24 [Server] INFO at bentobox.addon.challenges.panel.TryToComplete.checkSurrounding(TryToComplete.java:174) ~[?:?]
03.10 18:18:24 [Server] INFO at bentobox.addon.challenges.panel.TryToComplete.checkIfCanCompleteChallenge(TryToComplete.java:127) ~[?:?]
03.10 18:18:24 [Server] INFO at bentobox.addon.challenges.panel.TryToComplete.<init>(TryToComplete.java:59) ~[?:?]
03.10 18:18:24 [Server] INFO at bentobox.addon.challenges.panel.ChallengesPanels2.lambda$createItem$2(ChallengesPanels2.java:112) ~[?:?]
03.10 18:18:24 [Server] INFO at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:47) ~[?:?]
03.10 18:18:24 [Server] INFO at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_181]
03.10 18:18:24 [Server] INFO at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:45) ~[?:?]
03.10 18:18:24 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor900.execute(Unknown Source) ~[?:?]
03.10 18:18:24 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
`

**Comment by tastybento** [comment]
I'm pretty sure this was fixed already. Please try this version:

https://github.com/BentoBoxWorld/addon-challenges/releases
